#!/bin/bash

# place it in $HOME, since it is set in hypr.conf, make sure it is executable (chmod +x ./launch_bar)

if [[ ! $(pidof eww) ]]; then
	eww daemon
	sleep 1
fi

monitors=($(hyprctl monitors -j | jq -r '.[] | .id'))
for i in "${!monitors[@]}"; do
    # Use unique IDs for each bar by appending monitor ID
    bar_id="b${monitors[$i]}"
    # Open the bar for each monitor with a unique ID
    eww open --screen $i bar --id $bar_id
done


#monitors=($(hyprctl monitors -j | jq -r '.[] | .id'))
#for i in "${!monitors[@]}"; do
#	eww open --screen $i powermenu --id p$i
#	eww open --screen $i bar --id b$i
#	eww open --screen $i weather --id w$i
#done
